# Generated by Django 3.2.6 on 2021-08-19 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254)),
                ('text', models.TextField(default='')),
                ('create_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('update_date', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
