# Generated by Django 3.2.6 on 2021-08-19 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 14, 37, 56, 536899)),
        ),
        migrations.AlterField(
            model_name='message',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 14, 37, 56, 536922)),
        ),
    ]
