# Generated by Django 3.2.6 on 2021-08-19 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_auto_20210819_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 14, 39, 25, 845210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 14, 39, 25, 845248, tzinfo=utc)),
        ),
    ]
